spring:
  application:
    name:journal-App
  data:
    mongodb:
      uri:mongodb+srv://springstudent:springstudent@cluster0.sdlvg7n.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database:journaldb
      auto-index-creation=true


server:
  servlet:
    context-path:/journal
